### ISSUE TITLE
Pass by Reference

### ISSUE THREAD

**Issue by JBlond** [DigiLive/gitChangelog#3]
I think it makes so sense to pass $subject by reference the way it is used.

https://github.com/DigiLive/gitChangelog/blob/main/src/GitChangeLog.php#L397

**Comment by DigiLive** [comment]
I pushed other commits in the meantime.
Can you mention the new line?

**Comment by JBlond** [comment]
Now it is $subject https://github.com/DigiLive/gitChangelog/blob/main/src/GitChangeLog.php#L372 in function processCommitData()

**Comment by DigiLive** [comment]
If you trust on the message reported by PhpStorm, I think it's a false positive.
Within the foreach loop, the structure of the array it iterates, gets altered.
Without referencing, the foreach loop won't take over this changes.
