### ISSUE TITLE
PHP version bumped to 7.3

### ISSUE THREAD

**Issue by DigiLive** [DigiLive/gitChangelog#4]
@JBlond commented on commit 101b8fa the following:
> Well jblond/php-diff still uses PHP 7.2 and phpunit 8
> But we could change that to 7.3 since support for 7.2 is almost over. https://www.php.net/supported-versions.php

(https://github.com/DigiLive/gitChangelog/commit/101b8faa34fbae084eb0b342c25c02ff5d62fef4#commitcomment-43511535)

**Comment by DigiLive** [comment]
I was doubting about bumping to 7.3.
For the same reason and the use of PHPUnit v9, the version was bumped.

However the market share of php 7.2 (32%) is larger than 7.3 (28.1%), according to https://w3techs.com/technologies/details/pl-php/7
Let give it a thought which would be the better option... Bump php-diff to 7.3 or lower gitChangeLog to 7.2?
I'll be happy to lower the versions for the sake of php-diff.

**Comment by JBlond** [comment]
The php-diff lib requires PHP 7.2 or greater. Since this lib is only require-dev I don't see the need to lower the required PHP version for this lib. If you agree, you can close this issue.

**Comment by DigiLive** [comment]
From a php-lib perspective, you're right and I would agree.

From other users perspective, I'm still doubting because of the majority of market-share of 7.2
However I'm keen on sticking to 7.3 because of:

Branch | Initial Release | Active Support Until | Security Support Until
-- | -- | -- | --
7.2 | 30 Nov 2017 | 30 Nov 2019 | 30 Nov 2020 |

I still have to think it over. 😅

**Comment by JBlond** [comment]
From a windows user perspective I totally agree. On Linux it depends on the distro which version is supported.

debian version| php version|supported till
-- | --|--
Stretch 9 | 7.0| 2020 (2022-06)
Buster 10 | 7.3|2022 (2024)
unstable | 7.4|n/a

I don't know about the other distros.  So I think 7.3 is the way to go for both tools.

**Comment by DigiLive** [comment]
It's decided then... We'll stick to php ^7.3 and PhpUnit ^9 until it's time to bump again.
