### ISSUE TITLE
Roap map to Version 1.0.0

### ISSUE THREAD

**Issue by JBlond** [DigiLive/gitChangelog#6]
it would be nice to have a roadmap till version 1.0.0 to see what has to be done.

**Comment by DigiLive** [comment]
I understand the need of this.
Therefor I will stop develop new features or breaking changes until we both decided on a roadmap.

~~There's still PR #5 which I would like to finish though.~~

**Comment by DigiLive** [comment]
Please post each bug or feature request separately as an issue so i can assign them to [milestone 1](https://github.com/DigiLive/gitChangelog/milestone/1).
